### ISSUE TITLE
How to modify the spaCy NER or POS for Chinese which has no space as tokenization mark?

### ISSUE THREAD

**Issue by fishfree** [inception-project/inception-external-recommender#47]
spaCy has built-in automatically tokenization action before POS or NER when loading Chinese language  model such as zh_core_web_sm. But in the function predict() in the class [SpacyNerClassifier](https://github.com/inception-project/inception-external-recommender/blob/master/ariadne/contrib/spacy.py), it use tokenized list as the Doc class __init parameters.
```python
        # Extract the tokens from the CAS and create a spacy doc from it
        cas_tokens = cas.select(TOKEN_TYPE)
        words = [cas.get_covered_text(cas_token) for cas_token in cas_tokens]

        **doc = Doc(self._model.vocab, words=words)**

        # Find the named entities
        self._model.get_pipe("ner")(doc)
```
I cannot figure out how to just use the normal pipelines instead of "cas.select(TOKEN_TYPE)". Or to ask: which input parameter in the predict  funciton is the document?

**Comment by reckart** [comment]
If you want the document text instead of the tokens, you can use [`cas.sofa_string`](https://cassis.readthedocs.io/en/latest/api.html#cassis.Cas.sofa_string).

**Comment by fishfree** [comment]
@reckart Sorry to be at you again. Could you help me plsss? :-)

**Comment by fishfree** [comment]
@reckart OK, please point the doc. Thank you!

**Comment by reckart** [comment]
My understanding is that you want to pass the entire text of the document to some spacy function and you do not know how to get the entire text - try using [`cas.sofa_string`](https://cassis.readthedocs.io/en/latest/api.html#cassis.Cas.sofa_string). (note the link).

**Comment by fishfree** [comment]
@reckart Plese ignore my last reply. I just  found there is token type de.tudarmstadt.ukp.dkpro.core.mecab.type.JapaneseToken in the [file ](https://github.com/dkpro/dkpro-cassis/blob/445fa3a5e5c4d3f5e252417093557f0f71beb8a6/cassis/resources/dkpro-core-types.xml) So I change this into:
```python
        #cas_tokens = cas.select(TOKEN_TYPE)
        cas_tokens = cas.select('de.tudarmstadt.ukp.dkpro.core.mecab.type.JapaneseToken')
```
However, the error occurred as below:
 ![image](https://user-images.githubusercontent.com/1741341/232207256-07a06aea-d84d-4585-9ab6-56d7f2afb1fb.png)

**Comment by fishfree** [comment]
Thank you for your tip.
