### ISSUE TITLE
Placement of recommenders in the source tree

### ISSUE THREAD

**Issue by reckart** [inception-project/inception-external-recommender#5]
The recommender implementations currently seem to be a bit hidden under `ariadne/contrib`. People might rather look for them under `examples` or `scripts`. Is there a sensible way to make them more "prominent"?

Might also be nice to add a table overview over the available implementations to the README

**Comment by jcklie** [comment]
If you move it somewhere else, then you cannot import them anymore.

**Comment by jcklie** [comment]
I can rename it from contrib to examples, but for me these are not examples but actual usable recommenders that you do not need to touch in order to use them in production.

**Comment by jcklie** [comment]
I called it contrib because that it is how tensorflow calls it.
